spring:
  application:
    name: eurekaManagePage
server:
  port: 9090
eureka:
  instance:
    appname: eureka management page
  server:
    eviction-interval-timer-in-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
